### ISSUE TITLE
Run application multithreaded

### ISSUE THREAD

**Issue by aplaikner** [choopm/snmppp#2]
Hello there. Is it possible to run this application in a multithreaded way. If I want to scan a whole network for example.

**Comment by choopm** [comment]
The company I'm working for is using this in a network scanner. The crucial part is session handling, just make sure multiple threads don't share the same session (e.g. query the same switch) and you're good to go to scan all your switches/routers/etc in parallel.

**Comment by aplaikner** [comment]
Yes I've experienced some problems when using the net-snmp library in a multithreaded way. I do create a new session for every thread, but I get segfaults all the time.  Have you never had the problem?

**Comment by choopm** [comment]
net-snmp is a mess itself, we switched to this thin wrapper and contributed some things, it's not nice but it works. Use ASAN to see where your code crashes. Probably you're accessing the same session in 2 threads. Try sequential creation of sessions (openSession takes care by using a mutex) to avoid the snmp-init calls to race.
I know your struggles with that lib...

You got any code for me to reproduce?

**Comment by aplaikner** [comment]
I have thought of that too, but I sequentially create a new object for each session. By debugging further I've found out, that for some reason after a couple of threads being called, no new sessions are created, thus the segfault. 
Here I create new threads: https://github.com/V1leDev/ManInTheMirror/blob/Development/Scanner.cpp
Here I run the sessions: https://github.com/V1leDev/ManInTheMirror/blob/Development/Session.cpp
Maybe you can spot something I've failed to see.

**Comment by choopm** [comment]
I'll take a look this week once I find the time, I will highlight you for sure

**Comment by aplaikner** [comment]
This is my Dev branch: https://github.com/V1leDev/ManInTheMirror/tree/Development
If you remove the comments in Scanner::scan() and comment out session.start_session(); the code should run with threads. Compiler flags: -DCMAKE_CXX_FLAGS="-lnetsnmp -pthread"

**Comment by aplaikner** [comment]
Hi, I fixed the issue myself. I wanted to ask if you know of any way to receive and decode traps. Does this project support that?

**Comment by choopm** [comment]
Nice you fixed it yourself, I've been busy the whole time sry. This project is only implementing client functionality for now, there is code to send traps. Our workaround is to just start snmptrapd configured using our community and parse its output.
